### ISSUE TITLE
Threading

### ISSUE THREAD

**Issue by andris9** [wildduck-email/wildduck#12]
The most sane way for threading would probably be to add a separate reference collection that matches known threads to message-ids.

```
{
  _id: threadId,
  user: userId,
  ids: [list of message-ids],
  subject: 'normalized subject',
  updated: date
}
```

`updated` fields would have an index for `"expireAfterSeconds": 31104000` so old untouched references would be removed from the database after a year or so.

Checking thread value would look something like this:

```
// most messages are not threaded, so an upsert call should be ok to make
threads.findOneAndUpdate({
  user: userId,
  ids: {$in: ['message-id', 'references', 'in-reply-to']},
  subject: 'normalized subject'
}, {
  $addToSet: {
    ids: 'message-id' // maybe push all references etc as well?
  },
  $set: {
    user: userId,
    subject: 'normalized subject', // for the upster to work
    updated: new Date()
  }
}, {
    upsert: true,
    returnOriginal: false
})
```

**Comment by andris9** [comment]
In addition to message-id's, it would probably make sense to include Outlook threading values as well (https://developer.gnome.org/evolution-exchange/stable/ximian-connector-mail-threading.html)

**Comment by andris9** [comment]
Added by da967e13a67e18dead6c9f23f8109e1ff457661c

**Comment by andris9** [comment]
See also: https://tools.ietf.org/html/rfc5256

**Comment by iMuFeng** [comment]
This seems to be designed for IMAP,  doesn't seem so easy to query the database to realize threading.
