### ISSUE TITLE
Mail 'Proxy' ?

### ISSUE THREAD

**Issue by daslicht** [wildduck-email/wildduck#6]
Hi, 
could this be used to implement a kind of mail filtering proxy which reject hosts by a blacklist so that the spammer get a message that the host no longer exists or even a reject message  
and forward all other mails just to another mail server ?
Thats could be the solution to many spam issues :)

Cheers Marc

**Comment by andris9** [comment]
Wild Duck is a mailstore (IMAP). What you are thinking is a smart MTA (SMTP).
